name: Run sudo-bot to update files

permissions:
    contents: read

on:
    repository_dispatch:
        types: run-cron
    workflow_dispatch:

jobs:
    run-sudo-bot-cron:
        environment:
            name: sudo-bot
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use php 8.2
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.2
                  extensions: mailparse, pdo_pgsql, yaml

            - name: Update data
              run: php -f fetch-data.php
            - name: Qualify data
              run: php -f qualify-data.php
            - name: Update excuses
              run: php -f process-excuses.php
            - name: Install sudo-bot
              run: yarn global add sudo-bot
            - name: Extract secrets
              run: |
                  printf '%s' "${{ secrets.GH_APP_JWT_PRIV_PEM_CONTENTS }}" > ${HOME}/.secret_jwt.pem
                  printf '%s' "${{ secrets.GPG_PRIVATE_KEY }}" > ${HOME}/.private-key.asc
            - name: Run sudo-bot
              run: |
                  sudo-bot --verbose \
                    --jwt-file="${HOME}/.secret_jwt.pem" \
                    --gh-app-id='17453' \
                    --installation-id="${{ secrets.INSTALLATION_ID }}" \
                    --repository-slug='air-balloon/debian-dashboard' \
                    --target-branch='main' \
                    --assign='williamdes' \
                    --commit-author-email='sudo-bot@wdes.fr' \
                    --commit-author-name='Sudo Bot' \
                    --gpg-private-key-file="${HOME}/.private-key.asc" \
                    --gpg-private-key-passphrase="${{ secrets.GPG_PASSPHRASE }}"
            - name: Purge secrets
              if: always()
              run: |
                  rm -v ${HOME}/.secret_jwt.pem
                  rm -v ${HOME}/.private-key.asc
